/* eslint-disable @next/next/no-img-element */
import React from "react";
import Link from "next/link";
import AboutUs1Date from "../../data/sections/about-us1.json";

const termsandcondition = () => {
  return (
    <section className="about-us section-padding">
      <div className="container">
        <div className="row">
          <div className="col-lg-5 valign md-mb50">
            <h1>Terms & Condition</h1>
            <p>
              <h4>Acceptance of Terms:</h4>
              By accessing and using our website, you agree to be bound by these
              terms and conditions, including any future updates or
              modifications. If you do not agree with any part of these terms,
              please refrain from using our website or services.
              <h4>Intellectual Property:</h4>
              All intellectual property rights related to our website, products,
              and services, including but not limited to content, logos,
              trademarks, software, algorithms, and AI models, are owned by
              [Your Company Name] or our licensors. You acknowledge and agree
              that you do not acquire any ownership or intellectual property
              rights by using our website or services. You may not use, copy,
              reproduce, modify, distribute, or display any of our intellectual
              property without our prior written consent.
              <h4>User Responsibilities:</h4>
              By using our website and services, you agree to comply with
              applicable laws and regulations. You will not engage in any
              illegal, abusive, harmful, or fraudulent activities, including but
              not limited to unauthorized access, data breaches, reverse
              engineering, or infringing on the rights of others. You are solely
              responsible for the accuracy, legality, and quality of the data
              you provide to us.
              <h4>Limitation of Liability:</h4>
              To the maximum extent permitted by law, [Your Company Name] and
              its affiliates, directors, officers, employees, agents, and
              suppliers shall not be liable for any direct, indirect,
              incidental, consequential, or punitive damages arising out of or
              in connection with your use of our website, products, or services.
              We do not guarantee the accuracy, reliability, or completeness of
              any information provided on our website or generated by our AI
              products. You understand and agree that your use of our website
              and services is at your own risk.
              <h4>Termination:</h4>
              We reserve the right to terminate or suspend your access to our
              website and services, without prior notice or liability, for any
              reason, including but not limited to a breach of these terms and
              conditions or violation of applicable laws. Upon termination, your
              right to access or use our website and services will immediately
              cease.
              <h4>Governing Law and Jurisdiction:</h4>
              These terms and conditions shall be governed by and construed in
              accordance with the laws of [Your Jurisdiction]. Any disputes
              arising out of these terms and conditions or your use of our
              website shall be subject to the exclusive jurisdiction of the
              courts located in [Your Jurisdiction].
              <h4>Disclaimer:</h4>
              The information provided on our website is for general
              informational purposes only and should not be considered as
              professional advice. While we strive to ensure the accuracy and
              timeliness of the information, we make no warranties or
              representations regarding the accuracy, reliability, suitability,
              or completeness of the information. You acknowledge and agree that
              any reliance on the information provided is at your own risk. If
              you require more specific and detailed clauses or additional
              sections, its advisable to consult with a legal professional or
              attorney who can tailor the privacy policy and terms and
              conditions to meet your companys specific needs and comply with
              the relevant laws and regulations in your jurisdiction.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default termsandcondition;
